/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const GET_ALL_PRICES_STARTED = 'GET_ALL_PRICES_STARTED';
export const GET_ALL_PRICES_DONE = 'GET_ALL_PRICES_DONE';

export const HYDRATE_AUTH = 'HYDRATE_AUTH';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_DONE = 'LOGIN_DONE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_DONE = 'SIGNUP_DONE';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const GET_TRANSACTIONS_START = 'GET_TRANSACTIONS_START';
export const GET_TRANSACTIONS_DONE = 'GET_TRANSACTIONS_DONE';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';
